// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 这里提供回退值，只是为了通过 TypeScript 类型检查。
    // 真正运行时仍然优先读取 .env 中的 DATABASE_URL。
    url: process.env["DATABASE_URL"] ?? "file:/Users/hlstart/Ysport/PROJECT/ymt/prisma/dev.db",
  },
});
