PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  passwordHash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('MERCHANT', 'CONSUMER')),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE', 'DISABLED')),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MerchantProfile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL UNIQUE,
  shopName TEXT NOT NULL,
  contactName TEXT NOT NULL,
  contactPhone TEXT NOT NULL,
  address TEXT NOT NULL,
  description TEXT NOT NULL,
  coverImageUrl TEXT,
  status TEXT NOT NULL DEFAULT 'APPROVED' CHECK(status IN ('PENDING', 'APPROVED', 'REJECTED')),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Product (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  merchantId INTEGER NOT NULL,
  name TEXT NOT NULL,
  imageUrl TEXT,
  description TEXT NOT NULL,
  price REAL NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(merchantId) REFERENCES MerchantProfile(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Order" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  orderNo TEXT NOT NULL UNIQUE,
  consumerId INTEGER NOT NULL,
  merchantId INTEGER NOT NULL,
  totalAmount REAL NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED')),
  consigneeName TEXT NOT NULL,
  consigneePhone TEXT NOT NULL,
  consigneeAddress TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(consumerId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY(merchantId) REFERENCES MerchantProfile(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OrderItem (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  orderId INTEGER NOT NULL,
  productId INTEGER NOT NULL,
  productNameSnapshot TEXT NOT NULL,
  productImageSnapshot TEXT,
  unitPrice REAL NOT NULL,
  quantity INTEGER NOT NULL,
  lineAmount REAL NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(orderId) REFERENCES "Order"(id) ON DELETE CASCADE,
  FOREIGN KEY(productId) REFERENCES Product(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS Product_merchantId_idx ON Product(merchantId);
CREATE INDEX IF NOT EXISTS Product_status_idx ON Product(status);
CREATE INDEX IF NOT EXISTS Order_consumerId_idx ON "Order"(consumerId);
CREATE INDEX IF NOT EXISTS Order_merchantId_idx ON "Order"(merchantId);
CREATE INDEX IF NOT EXISTS Order_status_idx ON "Order"(status);
CREATE INDEX IF NOT EXISTS OrderItem_orderId_idx ON OrderItem(orderId);
